name: Display Name and Branch Details

on:
  push:
    branches:
      - Feature
      - Main

jobs:
  display_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display Your Name
        run: echo "Bhanu Prakash"

      - name: Display Branch Details
        id: branch_details
        run: |
          token=$GITHUB_TOKEN
          owner=$GITHUB_REPOSITORY_OWNER
          repo=$GITHUB_REPOSITORY_NAME

          branches=$(curl -s -H "Authorization: Bearer $token" "https://api.github.com/repos/$owner/$repo/branches")

          for branch in $(echo "$branches" | jq -r '.[] | .name'); do
            commit_details=$(curl -s -H "Authorization: Bearer $token" "https://api.github.com/repos/$owner/$repo/commits/$branch")
            last_commit_author=$(echo "$commit_details" | jq -r '.commit.author.name')
            last_commit_message=$(echo "$commit_details" | jq -r '.commit.message')
            last_commit_date=$(echo "$commit_details" | jq -r '.commit.author.date')

            echo "Branch: $branch"
            echo "  Last Commit Author: $last_commit_author"
            echo "  Last Commit Message: $last_commit_message"
            echo "  Last Commit Date: $last_commit_date"
            echo "----------"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.Sample }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
