name: Print My name
on: 
  pull_request:
    types: [opened]

jobs:
  print-name-and-merge:
  runs-on: ubuntu-latest

  steps:
  - name: Print name
    run: echo "Bhanu"

  - name: Checkout repository
    uses: actions/checkout@v2

  - name: Merge to Main
    if: github.event.pull_request.base.ref == 'main'
    run: |
      git config --global user.email "bhanu.prakashk994@gmail.com"
      git config --global user.name "Bhanu"
      git checkout main
      git merge --no-ff ${{ github.event.pull_request.head.ref }}
      git push origin main
