name: Display Name and Branch Details

on:
  pull_request:
    branches:
      - Feature
      - main

jobs:
  display_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display Your Name
        run: echo "Bhanu Prakash"

      - name: Display Branch Details
        id: branch_details
        run: |
          token=$GITHUB_TOKEN
          owner=$GITHUB_REPOSITORY_OWNER
          repo=$GITHUB_REPOSITORY_NAME

          response=$(curl -s -H "Authorization: Bearer $token" "https://api.github.com/repos/$owner/$repo/branches")
          echo "Branches:"
          echo "$response" | jq -r '.[] | "  Name: \(.name)\n    SHA: \(.commit.sha)\n    Last Commit: \(.commit.commit.author.name) - \(.commit.commit.message)\n    Date: \(.commit.commit.author.date)\n    Protected: \(.protected)\n    ----------"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
