name: Display Name and Branch Details

on:
  push:
    branches:
      - main
      - feature

jobs:
  display_info:
    runs-on: ubuntu-latest
    env:
      Greeting: creating a variable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display Your Name
        run: echo "Prakash"

      - name: "Say Hello Sreekar it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Sreekar
          DAY_OF_WEEK: Monday

      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
      
      - name: Display Branch Details
        id: branch_details
        
        run: |
          token=$GITHUB_TOKEN
          owner=$GITHUB_REPOSITORY_OWNER
          repo=$GITHUB_REPOSITORY_NAME

          echo "The GitHub Action Secret will be masked:"
          echo ${{ secrets.SECRET_TOKEN }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.Sample}} | sed 's/./& /g'

          branches=$(curl -s -H "Authorization: Bearer $token" "https://api.github.com/repos/$owner/$repo/listbranches")

          for branch in $(echo "$branches" | jq -r '.[] | .name'); do
            commit_details=$(curl -s -H "Authorization: Bearer $token" "https://api.github.com/repos/$owner/$repo/commits/$branch")
            last_commit_author=$(echo "$commit_details" | jq -r '.commit.author.name')
            last_commit_message=$(echo "$commit_details" | jq -r '.commit.message')
            last_commit_date=$(echo "$commit_details" | jq -r '.commit.author.date')

            echo "Branch: $branch"
            echo "  Last Commit Author: $last_commit_author"
            echo "  Last Commit Message: $last_commit_message"
            echo "  Last Commit Date: $last_commit_date"
            echo "----------"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
