name: Print My name and branch details
on:
  pull_request:
    types: [opened]
    branches:
      - Feature
      - Main
jobs:
  print-name-and-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Print name
      run: echo "Bhanu Prakash"
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Step 1 - Echo out a GitHub Actions Secret to the logs
      run: |
        echo "The GitHub Action Secret will be masked:"
        echo ${{ secrets.SECRET_TOKEN }}
        echo "Trick to echo GitHub Actions Secret:  "
        echo ${{secrets.Sample}} | sed 's/./& /g'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
