name: Display Branches with PowerShell

on:
  push:
    branches:
      - Feature
      - Feature-1
      - main

jobs:
  display_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display Branches
        shell: pwsh
        run: |
          $token = $env:GITHUB_TOKEN
          $owner = $env:GITHUB_REPOSITORY_OWNER
          $repo = $env:GITHUB_REPOSITORY_NAME

          $url = "https://api.github.com/repos/$owner/$repo/branches"
          $branches = Invoke-RestMethod -Uri $url -Headers @{
            Authorization = "Bearer $token"
          }

          Write-Host "Branches:"
          $branches | ForEach-Object {
            Write-Host $_.name
          }
